name:                matcher
version:             0.1.0.0
github:              "Arthi-chaud/Blee/matcher"
license:             GPL-3.0
author:              "Arthi-chaud"
copyright:           "2024 Arthi-chaud"

extra-source-files: []

description:         Please see the README on GitHub at <https://github.com/githubuser/matcher#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- OverloadedStrings
- DeriveGeneric

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - aeson
  - text
  - http-client
  - http-types
  - http-client-tls
  - bytestring

executables:
  matcher-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matcher
    - bytestring
    - amqp
    - text
    - aeson

tests:
  matcher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matcher
