FROM golang:1.22.1-bullseye
RUN go install github.com/bokwoon95/wgo@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN apt-get update -y; apt-get install -y libmediainfo-dev ffmpeg
WORKDIR /app

CMD "wgo" -xdir ./app/docs swag init -d app -o ./app/docs :: \
	go run ./app -d "$WATCH_DIR" -c "$CONFIG_DIR"/scanner.json
