name: blee
description: "Blee's Frontend app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.8.2
  flutter_riverpod: ^2.5.1
  flutter_sticky_header: ^0.6.5
  freezed_annotation: ^2.4.1
  go_router: ^13.2.4
  hexcolor: ^3.0.1
  http: ^1.2.1
  infinite_scroll_pagination: ^3.2.0
  json_annotation: ^4.8.1
  responsive_framework: ^1.4.0
  riverpod_annotation: ^2.3.5
  riverpod_infinite_scroll: ^1.0.9
  skeletonizer: ^1.1.2+1
  video_player: ^2.8.6
  video_player_web_hls: ^1.2.1
  mediametadata:
    path: ./mediametadata
  font_awesome_flutter: ^10.7.0
  uuid: ^4.4.0
  flutter_native_splash: ^2.4.0
  better_player: ^0.0.66

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  assets:
    - web/icons/Icon-192.png
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/rubik.ttf

flutter_native_splash:
  color: "#f5fafb"
  image: web/icons/Icon-512.png
  color_dark: "#0e1415"
  web: true
  web_image_mode: center
 