//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "external_id")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	#[sea_orm(column_type = "Text", nullable)]
	pub description: Option<String>,
	pub rating: Option<i16>,
	pub provider_name: String,
	pub value: String,
	pub url: String,
	pub registered_at: Date,
	pub artist_id: Option<Uuid>,
	pub package_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::artist::Entity",
		from = "Column::ArtistId",
		to = "super::artist::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Artist,
	#[sea_orm(
		belongs_to = "super::package::Entity",
		from = "Column::PackageId",
		to = "super::package::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Package,
}

impl Related<super::artist::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Artist.def()
	}
}

impl Related<super::package::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Package.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
