//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub mod prelude;

pub mod artist;
pub mod chapter;
pub mod extra;
pub mod file;
pub mod image;
pub mod movie;
pub mod package;
pub mod sea_orm_active_enums;
