//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "package")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	pub name: String,
	pub name_slug: String,
	#[sea_orm(unique)]
	pub unique_slug: String,
	pub release_year: Option<Date>,
	pub registered_at: Date,
	pub artist_id: Option<Uuid>,
	pub poster_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::artist::Entity",
		from = "Column::ArtistId",
		to = "super::artist::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Artist,
	#[sea_orm(has_many = "super::external_id::Entity")]
	ExternalId,
	#[sea_orm(has_many = "super::extra::Entity")]
	Extra,
	#[sea_orm(
		belongs_to = "super::image::Entity",
		from = "Column::PosterId",
		to = "super::image::Column::Id",
		on_update = "NoAction",
		on_delete = "SetNull"
	)]
	Image,
	#[sea_orm(has_many = "super::movie::Entity")]
	Movie,
}

impl Related<super::artist::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Artist.def()
	}
}

impl Related<super::external_id::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ExternalId.def()
	}
}

impl Related<super::extra::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Extra.def()
	}
}

impl Related<super::image::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Image.def()
	}
}

impl Related<super::movie::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Movie.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
