//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::artist::Entity as Artist;
pub use super::chapter::Entity as Chapter;
pub use super::extra::Entity as Extra;
pub use super::file::Entity as File;
pub use super::image::Entity as Image;
pub use super::movie::Entity as Movie;
pub use super::package::Entity as Package;
