name: 'Cache (API)'
description: 'Cache for API'
runs:
  using: "composite"
  steps:
    - name: Setup Rust
      shell: bash
      run: rustup toolchain install stable --profile minimal
    # Src: https://github.com/marketplace/actions/rust-cache
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: ""
        shared-key: ""
        key: ""
        cache-directories: "./api/target"
        cache-on-failure: true
        cache-all-crates: true