name: 'Cache (API)'
description: 'Cache for API'
runs:
  using: "composite"
  steps:
    - name: Setup Rust
      shell: bash
      run: rustup toolchain install stable --profile minimal
    - uses: actions/cache@v3
      name: Cache ~/.cargo
      with:
        path: ~/.cargo
        key: cargo-global
        restore-keys: |
          cargo-global
    - uses: actions/cache@v3
      name: Cache target
      with:
        path: api/target
        key: cargo-target
        restore-keys: |
          cargo-target