name: 'Cache (Front)'
description: 'Cache for Front'
runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v3
      with:
          path: |
            ./front/node_modules
            ./front/.output
            ./front/.nuxt
          key: front
          restore-keys: front