[package]
name = "blee-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
rocket_okapi = { features = [ "swagger", "rapidoc" ] }
serde = "1.0"